"""Apply the frozen Stage B grounded-JEPA gate."""
from __future__ import annotations
import argparse,importlib.util,json,sys
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/"src"))
from wmagentattack.multisource_suitability import file_sha256
spec=importlib.util.spec_from_file_location("sa",ROOT/"scripts/206_summarize_relational_slot_stage_a.py");sa=importlib.util.module_from_spec(spec);spec.loader.exec_module(sa)
def main():
 p=argparse.ArgumentParser();p.add_argument("--protocol",type=Path,required=True);p.add_argument("--predictions",type=Path,required=True);p.add_argument("--run-metrics",type=Path,required=True);p.add_argument("--output",type=Path,required=True);p.add_argument("--markdown",type=Path,required=True);args=p.parse_args();protocol=json.loads(args.protocol.read_text());rows=sa.read(args.predictions);metrics=json.loads(args.run_metrics.read_text());stage_a=sa.read(protocol["external_stage_a_control"]["predictions"])
 if file_sha256(Path(protocol["external_stage_a_control"]["predictions"]))!=protocol["external_stage_a_control"]["sha256"]:raise ValueError("Stage A hash mismatch")
 baseline=[r for r in rows if r["arm"]=="v6_replication_stage_b"];candidate=[r for r in rows if r["arm"]=="grounded_jepa_stage_b"]
 h1b=[r for r in baseline if r["horizon"]==1];h1c=[r for r in candidate if r["horizon"]==1];mb=[r for r in baseline if r["horizon"]>=2];mc=[r for r in candidate if r["horizon"]>=2];ja=[r for r in stage_a if r["arm"]=="relational_slot_stage_a" and r["horizon"]>=2];jb=[r for r in mb if r["joint_trainable"]];jc=[r for r in mc if r["joint_trainable"]]
 effects={"h1_nll":sa.effect(h1b,h1c,"action_nll"),"h1_accuracy":sa.effect(h1b,h1c,"action_correct",True),"h2_h5_vs_v6":sa.effect(mb,mc,"action_nll"),"h2_h5_vs_stage_a":sa.effect(ja,mc,"action_nll"),"future_joint_ce":sa.effect(jb,jc,"joint_ce")}
 std=float(np.mean([r["slot_std_mean"] for r in metrics["runs"]]));low=float(np.mean([r["low_variance_fraction"] for r in metrics["runs"]]));gate=protocol["stage_b"]["gate"]
 checks={"h1_nll_noninferiority":effects["h1_nll"]["mean"]>=-gate["maximum_h1_nll_degradation_vs_v6"],"h1_accuracy_noninferiority":effects["h1_accuracy"]["mean"]>=-gate["maximum_h1_accuracy_degradation_vs_v6"],"h2_h5_gain_vs_v6":effects["h2_h5_vs_v6"]["mean"]>=gate["minimum_h2_h5_nll_gain_vs_v6"],"h2_h5_gain_vs_stage_a":effects["h2_h5_vs_stage_a"]["mean"]>=gate["minimum_h2_h5_nll_gain_vs_stage_a"],"h2_h5_task_breadth":effects["h2_h5_vs_v6"]["positive"]>=gate["minimum_h2_h5_positive_task_fraction"],"h2_h5_seed_replication":sum(value>=gate["minimum_h2_h5_nll_gain_vs_v6"] for value in effects["h2_h5_vs_v6"]["seeds"].values())>=gate["minimum_threshold_positive_seeds"],"future_joint_noninferiority":effects["future_joint_ce"]["mean"]>=-gate["maximum_future_joint_ce_degradation"],"anti_collapse":std>=gate["minimum_slot_dimension_mean_std"] and low<=gate["maximum_low_variance_dimension_fraction"],"all_legal":all(r["legal_prediction"]==1 for r in rows),"complete_budget":metrics["teacher_fits"]==metrics["v6_residual_fits"]==metrics["grounded_jepa_fits"]==15 and metrics["runtime_failures"]==0}
 decision="GO_GROUNDED_JEPA_STAGE_B" if all(checks.values()) else "NO_GO_GROUNDED_JEPA_STAGE_B";summary={"protocol_id":protocol["protocol_id"],"decision":decision,"checks":checks,"effects":effects,"latent_diagnostics":{"slot_dimension_mean_std":std,"low_variance_dimension_fraction":low},"absolute":{"v6_h1_nll":sa.macro(h1b,"action_nll"),"jepa_h1_nll":sa.macro(h1c,"action_nll"),"v6_h1_accuracy":sa.macro(h1b,"action_correct"),"jepa_h1_accuracy":sa.macro(h1c,"action_correct"),"v6_h2_h5_nll":sa.macro(mb,"action_nll"),"jepa_h2_h5_nll":sa.macro(mc,"action_nll"),"stage_a_h2_h5_nll":sa.macro(ja,"action_nll"),"v6_future_joint_ce":sa.macro(jb,"joint_ce"),"jepa_future_joint_ce":sa.macro(jc,"joint_ce")},"predictions_sha256":file_sha256(args.predictions),"run_metrics_sha256":file_sha256(args.run_metrics)};args.output.write_text(json.dumps(summary,indent=2,sort_keys=True)+"\n");args.markdown.write_text("# Grounded JEPA Stage B\n\nDecision: `"+decision+"`\n\n"+"\n".join(f"- {key}: {'PASS' if value else 'FAIL'}" for key,value in checks.items())+"\n")
if __name__=="__main__":main()
