"""Apply the frozen successor-affordance C2 gate."""
from __future__ import annotations
import argparse,importlib.util,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/"src"))
from wmagentattack.multisource_suitability import file_sha256
def load(name,path):
 s=importlib.util.spec_from_file_location(name,path);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
c1sum=load("c1sum",ROOT/"scripts/211_summarize_interface_affordance_c1.py")
def main():
 p=argparse.ArgumentParser();p.add_argument("--protocol",type=Path,required=True);p.add_argument("--predictions",type=Path,required=True);p.add_argument("--run-metrics",type=Path,required=True);p.add_argument("--output",type=Path,required=True);p.add_argument("--markdown",type=Path,required=True);a=p.parse_args();protocol=json.loads(a.protocol.read_text());rows=c1sum.read(a.predictions);metrics=json.loads(a.run_metrics.read_text());v6=c1sum.read(protocol["external_v6_control"]["predictions"]);c1=c1sum.read(protocol["external_stage_c1_control"]["predictions"])
 if file_sha256(Path(protocol["external_v6_control"]["predictions"]))!=protocol["external_v6_control"]["sha256"] or file_sha256(Path(protocol["external_stage_c1_control"]["predictions"]))!=protocol["external_stage_c1_control"]["sha256"]:raise ValueError("external control mismatch")
 base=[r for r in v6 if r["arm"]=="structured_residual_v6"];prior=[r for r in c1 if r["arm"]=="interface_affordance_c1"];cand=[r for r in rows if r["arm"]=="successor_affordance_c2"]
 h1b=[r for r in base if r["horizon"]==1];h1c=[r for r in cand if r["horizon"]==1];mb=[r for r in base if r["horizon"]>=2];mp=[r for r in prior if r["horizon"]>=2];mc=[r for r in cand if r["horizon"]>=2];jb=[r for r in mb if r["joint_trainable"]];jc=[r for r in mc if r["joint_trainable"]]
 effects={"h1_nll":c1sum.effect(h1b,h1c,"action_nll"),"h1_accuracy":c1sum.effect(h1b,h1c,"action_correct",True),"h2_h5_nll_vs_v6":c1sum.effect(mb,mc,"action_nll"),"h2_h5_nll_vs_c1":c1sum.effect(mp,mc,"action_nll"),"future_joint_ce":c1sum.effect(jb,jc,"joint_ce")};g=protocol["stage_c2"]["gate"];audit=metrics["slot_audit"]
 checks={"h1_nll_noninferiority":effects["h1_nll"]["mean"]>=-g["maximum_h1_nll_degradation_vs_v6"],"h1_accuracy_noninferiority":effects["h1_accuracy"]["mean"]>=-g["maximum_h1_accuracy_degradation_vs_v6"],"h2_h5_gain_vs_v6":effects["h2_h5_nll_vs_v6"]["mean"]>=g["minimum_h2_h5_nll_gain_vs_v6"],"h2_h5_gain_vs_c1":effects["h2_h5_nll_vs_c1"]["mean"]>=g["minimum_h2_h5_nll_gain_vs_stage_c1"],"h2_h5_task_breadth":effects["h2_h5_nll_vs_v6"]["positive"]>=g["minimum_h2_h5_positive_task_fraction"],"h2_h5_seed_replication":sum(v>=g["minimum_h2_h5_nll_gain_vs_v6"] for v in effects["h2_h5_nll_vs_v6"]["seeds"].values())>=g["minimum_threshold_positive_seeds"],"future_joint_noninferiority":effects["future_joint_ce"]["mean"]>=-g["maximum_future_joint_ce_degradation"],"bottleneck_integrity":not audit["raw_values_encoded"] and audit["interface_only_lexical_encoding"] and audit["unmatched_text_tokens_encoded"]==audit["truncated_rows"]==audit["concept_truncated_rows"]==0,"all_legal":all(r["legal_prediction"]==1 for r in cand),"complete_budget":metrics["teacher_fits"]==metrics["successor_affordance_residual_fits"]==15 and metrics["runtime_failures"]==0}
 decision="GO_SUCCESSOR_AFFORDANCE_C2" if all(checks.values()) else "NO_GO_SUCCESSOR_AFFORDANCE_C2";summary={"protocol_id":protocol["protocol_id"],"decision":decision,"checks":checks,"effects":effects,"absolute":{"v6_h1_nll":c1sum.macro(h1b,"action_nll"),"candidate_h1_nll":c1sum.macro(h1c,"action_nll"),"v6_h1_accuracy":c1sum.macro(h1b,"action_correct"),"candidate_h1_accuracy":c1sum.macro(h1c,"action_correct"),"v6_h2_h5_nll":c1sum.macro(mb,"action_nll"),"c1_h2_h5_nll":c1sum.macro(mp,"action_nll"),"candidate_h2_h5_nll":c1sum.macro(mc,"action_nll"),"v6_future_joint_ce":c1sum.macro(jb,"joint_ce"),"candidate_future_joint_ce":c1sum.macro(jc,"joint_ce")},"predictions_sha256":file_sha256(a.predictions),"run_metrics_sha256":file_sha256(a.run_metrics)};a.output.write_text(json.dumps(summary,indent=2,sort_keys=True)+"\n");a.markdown.write_text("# Successor affordance C2\n\nDecision: `"+decision+"`\n\n"+"\n".join(f"- {k}: {'PASS' if v else 'FAIL'}" for k,v in checks.items())+"\n")
if __name__=="__main__":main()
